language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: cty4l06kZB4NgprXEyN0jFdwngE5aOm5gREm0PLG4T6A44VKFZiRFdvBTYFdMNtYqoE7Oq1iAMdkAyqWgQ4bUCJqqRPxoHOmB94vbxT5un6daTq6R5crmPkCQB3zqtLqNKN4HYDXS5+fg3vkiPiHhYdfCwIACq4P6JPB42C9iopLMhtBAdocw68o+rAl5JJ0IKBA9KjY32Qr5bnEJSNhkVvyFWezsQl9CNDL6RJlrfjLwIkGQwv6TuYSq2yGj8+MV4BQdVmK01+Mvzkrnbn7AmABcAoqL973q34N4lxdZ4arzv+N/id4l6t3FgCxvR0ES/DmjtbEHgZzz22ScvxVMT2Z9LyZSqj/Ghc7hp0ei8zl+wq6ja0HEm93rQK4mvLxROn9eBzerHEeG0hLrRvlxgXyuM/U5H6PJ9Vh3dU4iYo2lX/i2xxMJWpXgH3zvsAiNgTNCyW1Y3ylbAjgak4OpHjJnHR3U5KmXL5q89Sgv9eM7Gsm1KsP0u2Lg0F13mCuvH9QU3qFseUFJSmCviSHvcenxV4nSmCr3703J+4C7pkonI5cxtlfP/kxpMhg3i1ki9VcHkfoWFeKeOlpJ1C9bgXRCTaOJhRDN9kErhrmR6stT6EUMDGZ3jev0XofturO6sdyv+KSYWfolQWYQ7BxqLh/9fRSyjsWgIaaSRpgjCQ=
  app: polar-mesa-46913
  on:
    repo: thinkful-ei24/cameron-noteful-v3
